# week4 授業前課題3 オブジェクト指向の活用

## 【問題1】これまで利用してきたクラスの列挙
クラスを使う際はインスタンス化を行うことと、クラスの命名法がわかりました。<br>
この情報を元に、これまでの課題で利用してきたコードの中でどのようなクラスがあったかを答えてください。<br>
Pandas、matplotlib、scikit-learnからそれぞれ1つ以上見つけてください。

【回答】<br>
- pandas.DataFrame
- matplotlib.figure.Figure
- sklearn.tree.DecisionTreeRegressor

## 【問題2】これまで利用してきたメソッドやインスタンス変数の列挙
これまでの課題で利用してきたコードの中でどのようなメソッドやインスタンス変数があったかを答えてください。<br>
最低でもそれぞれ5つ以上答えてください。

【回答】<br>
メソッド
- pandas.DataFrame.info()
- numpy.sin()
- matplotlib.pyplot.plt()
- sklearn.tree.DecisionTreeRegressor.fit()
- len()

インスタンス変数
- pandas.DataFrame.columns
- pandas.DataFrame.iloc
- sklearn.linear_model.LinearRegression.self.copy_X
- numpy.array.dtype
- numpy.array.size

## 【問題3】標準化クラスをスクラッチで作成

In [59]:
# StandardScalerの挙動
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.datasets import load_iris
data = load_iris()
X = data.data[:10]
scaler = StandardScaler()
scaler.fit(X)
print("平均 :", scaler.mean_)
print("分散 :", scaler.var_)
X_std = scaler.transform(X)
print("標準化 :", X_std)

平均 : [4.86 3.31 1.45 0.22]
分散 : [0.0764 0.0849 0.0105 0.0056]
標準化 : [[ 0.86828953  0.65207831 -0.48795004 -0.26726124]
 [ 0.14471492 -1.06391725 -0.48795004 -0.26726124]
 [-0.57885968 -0.37751902 -1.46385011 -0.26726124]
 [-0.94064699 -0.72071813  0.48795004 -0.26726124]
 [ 0.50650222  0.99527742 -0.48795004 -0.26726124]
 [ 1.95365143  2.02487476  2.43975018  2.40535118]
 [-0.94064699  0.3088792  -0.48795004  1.06904497]
 [ 0.50650222  0.3088792   0.48795004 -0.26726124]
 [-1.66422159 -1.40711636 -0.48795004 -0.26726124]
 [ 0.14471492 -0.72071813  0.48795004 -1.60356745]]


### スクラッチ

In [57]:
class ScratchStandardScaler():
    """
    標準化のためのクラス
    Attributes
    -------------
    mean_ : 次の形のndarray, shape(n_features,) 平均
    ss_       : 平方和
    var_     : 次の形のndarray, shape(n_features,) 分散
    s_         : 標準偏差
    """
        
    def fit(self, X):
        """
        標準化のために平均と標準偏差を計算する
        Parameters
        --------------
        X :次の形のndarray, shape(n_samples, n_features) 訓練データ
        """
        
        self.mean_ = X.mean(axis=0)
        self.ss_ = np.sum((X - self.mean_)**2, axis=0)
        self.var_ = self.ss_ / len(X)
        self.s_ = np.sqrt(self.var_)
        pass
    def transform(self, X):
        """
        fitで求めた値を使い標準化を行う
        Parameters
        --------------
        X: 次の形のndarray, shape(n_samples, n_features) 特徴量
        Returns
        --------------
        X_scaled :次の形のndarray, shape(n_samples, n_features) 標準化された特徴量
        """
        # 標準化= (個々のデータ - 平均)/標準偏差
        X_scaled = (X - self.mean_) / self.s_
        pass
        return X_scaled
    

In [58]:
import numpy as np
from sklearn.datasets import load_iris
data = load_iris()
X = data.data[: 10]
scratch_scaler = ScratchStandardScaler()
scratch_scaler.fit(X)
print("平均 ： {}".format(scratch_scaler.mean_))
print("平方和 ： {}".format(scratch_scaler.ss_))
print("分散 ： {}".format(scratch_scaler.var_))
print("標準偏差 ： {}".format(scratch_scaler.s_))
X_std = scratch_scaler.transform(X)
print("標準化：{}".format(X_std))

平均 ： [4.86 3.31 1.45 0.22]
平方和 ： [0.764 0.849 0.105 0.056]
分散 ： [0.0764 0.0849 0.0105 0.0056]
標準偏差 ： [0.2764055  0.29137605 0.10246951 0.07483315]
標準化：[[ 0.86828953  0.65207831 -0.48795004 -0.26726124]
 [ 0.14471492 -1.06391725 -0.48795004 -0.26726124]
 [-0.57885968 -0.37751902 -1.46385011 -0.26726124]
 [-0.94064699 -0.72071813  0.48795004 -0.26726124]
 [ 0.50650222  0.99527742 -0.48795004 -0.26726124]
 [ 1.95365143  2.02487476  2.43975018  2.40535118]
 [-0.94064699  0.3088792  -0.48795004  1.06904497]
 [ 0.50650222  0.3088792   0.48795004 -0.26726124]
 [-1.66422159 -1.40711636 -0.48795004 -0.26726124]
 [ 0.14471492 -0.72071813  0.48795004 -1.60356745]]


## 【問題4】 四則演算を行うクラスの作成
上記ExampleClassは足し算のメソッドを持っていますが、これに引き算、掛け算、割り算のメソッドを加えてください。<br>
コンストラクタに入力されたvalueが文字列や配列など数値以外だった場合にはエラーを出すようにしてください。<br>
クラス名や説明文も適切に書き換えてください。<br>

In [77]:
class ExampleClass():
    """
    四則演算を行うクラス
    
    Parameters
    --------------
    value : float or int
    　　　　初期値
    
    Attributes(属性)
    -------------
    value : float or int
    　　　　計算結果
    """
    def __init__(self, value):
        self.value = value
        print("初期値{}が設定されました".format(self.value))
    def add(self, value2):
        """
        受け取った引数をself.valueに加える
        """
        if not isinstance(value2, (int, float)):
            warnings.warn("数値を入れてください")
        else:
            self.value += value2
    def subtraction(self, value2):
        """
        受け取った引数をself.valueから引く
        """
        if not isinstance(value2, (int, float)):
            warnings.warn("数値を入れてください")
        else:
            self.value -= value2
    def multiplication(self, value2):
        """
        受け取った引数をself.valueにかける
        """
        if not isinstance(value2, (int, float)):
            warnings.warn("数値を入れてください")
        else:
            self.value *= value2
    
    def division(self, value2):
        """
        受け取った引数でself.valueを割る
        """
        if not isinstance(value2, (int, float)):
            warnings.warn("数値を入れてください")
        else:
            self.value /= value2

In [78]:
import warnings
example = ExampleClass(5)
print("value  :  {}".format(example.value))
example.add(3)
print("value  :  {}".format(example.value))
example.subtraction(2)
print("value  :  {}".format(example.value))
example.multiplication(3)
print("value  :  {}".format(example.value))
example.division(3)
print("value  :  {}".format(example.value))
example.multiplication("str")
print("value  :  {}".format(example.value))

初期値5が設定されました
value  :  5
value  :  8
value  :  6
value  :  18
value  :  6.0
value  :  6.0


/Users/arisa/.pyenv/versions/anaconda3-5.3.1/lib/python3.7/site-packages/ipykernel_launcher.py:39: UserWarning: 数値を入れてください
