# week2 授業前課題3 行列積のスクラッチ

以下のような行列A、Bを考えます。
$$
A=\begin{bmatrix}
-1 & 2 & 3 \\
4 & -5 & 6 \\
7 & 8 & -9 \\
\end{bmatrix}
,B=\begin{bmatrix}
0 & 2 & 1 \\
0 & 2 & -8 \\
2 & 9 & -1 \\
\end{bmatrix}
$$
NumPyで表すと次のようになります。

In [9]:
import numpy as np
a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])

## 【問題1】行列積を手計算する
AとBの行列積を手計算で解いてください。<br>
計算過程もマークダウンテキストを用いて説明してください。

$$
AB=\begin{bmatrix}
-1\times0 + 2\times0 + 3\times 2  & -1\times2 + 2\times2 + 3\times9 & -1\times1 + 2\times-8 + 3\times-1 \\
4\times0 + -5\times0 + 6\times2 & 4\times2 + -5\times2 + 6\times9 & 4\times1 + -5\times-8 + 6\times-1 \\
7\times0 + 8\times0 + -9\times2 & 7\times2 + 8\times2 + -9\times9 & 7 \times1 + 8\times-8 + -9\times-1 \\
\end{bmatrix}
$$

$$
=\begin{bmatrix}
6 & 29 & -20 \\
12 & 52 & 38 \\
-18 & 51 & -48 \\
\end{bmatrix}
$$

## 【問題2】NumPyの関数による計算
この行列積はNumPyのnp.matmul()やnp.dot()、または@演算子を使うことで簡単に計算できます。<br>
これらを使い行列積を計算してください。

In [12]:
# np.matmul()
np.matmul(a_ndarray, b_ndarray)

array([[  6,  29, -20],
       [ 12,  52,  38],
       [-18, -51, -48]])

In [13]:
# np.dot()
np.dot(a_ndarray, b_ndarray)

array([[  6,  29, -20],
       [ 12,  52,  38],
       [-18, -51, -48]])

In [15]:
# @
a_ndarray@b_ndarray

array([[  6,  29, -20],
       [ 12,  52,  38],
       [-18, -51, -48]])

## 【問題3】ある要素の計算を実装
手計算をする際はまず行列Aの0行目と行列Bの0列目に注目し、以下の計算を行ったかと思います。
1、行列Aの(0,0)の要素と行列Bの(0,0)の要素を掛け合わせる<br>
2、行列Aの(0,1)の要素と行列Bの(1,0)の要素を掛け合わせる<br>
3、行列Aの(0,2)の要素と行列Bの(2,0)の要素を掛け合わせる<br>
4、それらの値を全て足し合わせる<br>
数式で表すと
$$
\sum_{k=0}^{2}a_{0,k}b_{k,0}
$$
です。
この計算をnp.matmul()やnp.dot()、または@演算子を使わずに行うコードを書いてください。

In [17]:
ans = 0
for k in range(0, 3):
    ans += a_ndarray[0][k]*b_ndarray[k][0]
print(ans)

6


## 【問題4】行列積を行う関数の作成
問題3のコードを拡張し、行列積のスクラッチ実装を完成させてください。行列AとBを引数に受け取り、行列積を返す関数としてください。<br>
行列積を計算する場合は、問題3の計算を異なる行や列に対して繰り返していくことになります。<br>
計算結果である 3×3の行列Cの各要素Ci,jは数式で表すと次のようになります。<br>
$$
c_{i,j} = \sum_{k=0}^{2}a_{i,k}b_{k,j}
$$

for文を使い、ndarrayのインデックスを動かしていくことで、合計9つの要素が計算できます。<br>
インデックス iや jを1増やすと、次の行や列に移ることができます。

In [97]:
# 3x3行列と3x3行列の行列積以外にも対応する
def matrix_times(a_ndarray, b_ndarray):
    # 行[:, -1]　列[-1] 
    if len(a_ndarray[-1]) != len(b_ndarray[:, -1]):
        print("Error:1つ目行列の列サイズと２つ目の行列の行サイズを同じにしてから実行してください")
        pass
    else:
        matrix_list = []
        # 1つめの行列の行でループ
        for i in range(len(a_ndarray[:, -1])):
            # 2つめの行列の列でループ
            for j in range(len(b_ndarray[-1])):
                # 1つめの列と２つめの行は同じサイズ
                youso = 0
                for k in range(len(a_ndarray[-1])):
                    youso += a_ndarray[i][k]*b_ndarray[k][j]
                matrix_list.append(youso)
        list_ndarray = np.array(matrix_list)
        matrix_ndarray = list_ndarray.reshape(len(a_ndarray[:, -1]), len(b_ndarray[-1]))
        return matrix_ndarray

In [98]:
# 問題1の行列A、Bの積
matrix_ndarray = matrix_times(a_ndarray, b_ndarray)
print(matrix_ndarray)

[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]


In [99]:
# 3x2行列と2x2行列の積
c_ndarray = np.array([[1, 2], [3, 4], [5, 6]])
d_ndarray = np.array([[7, 8], [10, 11]])
matrix_ndarray = matrix_times(c_ndarray, d_ndarray)
print(matrix_ndarray)
# 答え合わせ
np.dot(c_ndarray, d_ndarray)

[[ 27  30]
 [ 61  68]
 [ 95 106]]


array([[ 27,  30],
       [ 61,  68],
       [ 95, 106]])

In [100]:
# 3x2行列と2x3行列の積
c_ndarray = np.array([[1, 2], [3, 4], [5, 6]])
d_ndarray = np.array([[7, 8, 9], [10, 11, 12]])
matrix_ndarray = matrix_times(c_ndarray, d_ndarray)
print(matrix_ndarray)
# 答え合わせ
np.dot(c_ndarray, d_ndarray)

[[ 27  30  33]
 [ 61  68  75]
 [ 95 106 117]]


array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]])

In [103]:
# 計算できない行列積
d_ndarray = np.array([[-1, 2, 3], [4, -5, 6]])
e_ndarray = np.array([[-9, 8, 7], [6, -5, 4]])
matrix_ndarray = matrix_times(d_ndarray, e_ndarray)
print(matrix_ndarray)

Error:1つ目行列の列サイズと２つ目の行列の行サイズを同じにしてから実行してください
None


## 【問題5】計算が定義されない入力を判定する
問題4で作成した関数は、実装方法によってはこのDとEの配列を入力しても動いてしまう可能性があります。<br>
この場合、不適切な計算が行われることになります。<br>
また、途中でエラーになる場合でも、なぜエラーになったかが直接的には分かりづらいメッセージが表示されます。<br>
if文などによってこれを防ぎ、入力される形に問題があることをprint()を使い表示するコードを書き加えてください。<br>

### 問題5の回答はすでに問題4で実装済みです


## 【問題6】転置
片方の行列を転置することで、行列積が計算できるようになります。<br>
np.transpose()や.Tアトリビュートを用いて転置し、行列積を計算してください。

In [106]:
matrix_ndarray = matrix_times(d_ndarray.T, e_ndarray)
print(matrix_ndarray)
# 答え合わせ
np.dot(d_ndarray.T, e_ndarray)

[[ 33 -28   9]
 [-48  41  -6]
 [  9  -6  45]]


array([[ 33, -28,   9],
       [-48,  41,  -6],
       [  9,  -6,  45]])